export const AUDIO_MAP = {
	piece: {
		k: 'piece/king.mp3',
		q: 'piece/queen.mp3',
		r: 'piece/rook.mp3',
		b: 'piece/bishop.mp3',
		n: 'piece/knight.mp3',
		p: 'piece/pawn.mp3',
	},
	color: {
		w: 'color/white.mp3',
		b: 'color/black.mp3',
	},
	file: {
		a: 'file/a.mp3',
		b: 'file/b.mp3',
		c: 'file/c.mp3',
		d: 'file/d.mp3',
		e: 'file/e.mp3',
		f: 'file/f.mp3',
		g: 'file/g.mp3',
		h: 'file/h.mp3',
	},
	rank: {
		['1']: 'rank/1.mp3',
		['2']: 'rank/2.mp3',
		['3']: 'rank/3.mp3',
		['4']: 'rank/4.mp3',
		['5']: 'rank/5.mp3',
		['6']: 'rank/6.mp3',
		['7']: 'rank/7.mp3',
		['8']: 'rank/8.mp3',
	},
	square: {
		a1: 'square/a1.mp3',
		a2: 'square/a2.mp3',
		a3: 'square/a3.mp3',
		a4: 'square/a4.mp3',
		a5: 'square/a5.mp3',
		a6: 'square/a6.mp3',
		a7: 'square/a7.mp3',
		a8: 'square/a8.mp3',
		b1: 'square/b1.mp3',
		b2: 'square/b2.mp3',
		b3: 'square/b3.mp3',
		b4: 'square/b4.mp3',
		b5: 'square/b5.mp3',
		b6: 'square/b6.mp3',
		b7: 'square/b7.mp3',
		b8: 'square/b8.mp3',
		c1: 'square/c1.mp3',
		c2: 'square/c2.mp3',
		c3: 'square/c3.mp3',
		c4: 'square/c4.mp3',
		c5: 'square/c5.mp3',
		c6: 'square/c6.mp3',
		c7: 'square/c7.mp3',
		c8: 'square/c8.mp3',
		d1: 'square/d1.mp3',
		d2: 'square/d2.mp3',
		d3: 'square/d3.mp3',
		d4: 'square/d4.mp3',
		d5: 'square/d5.mp3',
		d6: 'square/d6.mp3',
		d7: 'square/d7.mp3',
		d8: 'square/d8.mp3',
		e1: 'square/e1.mp3',
		e2: 'square/e2.mp3',
		e3: 'square/e3.mp3',
		e4: 'square/e4.mp3',
		e5: 'square/e5.mp3',
		e6: 'square/e6.mp3',
		e7: 'square/e7.mp3',
		e8: 'square/e8.mp3',
		f1: 'square/f1.mp3',
		f2: 'square/f2.mp3',
		f3: 'square/f3.mp3',
		f4: 'square/f4.mp3',
		f5: 'square/f5.mp3',
		f6: 'square/f6.mp3',
		f7: 'square/f7.mp3',
		f8: 'square/f8.mp3',
		g1: 'square/g1.mp3',
		g2: 'square/g2.mp3',
		g3: 'square/g3.mp3',
		g4: 'square/g4.mp3',
		g5: 'square/g5.mp3',
		g6: 'square/g6.mp3',
		g7: 'square/g7.mp3',
		g8: 'square/g8.mp3',
		h1: 'square/h1.mp3',
		h2: 'square/h2.mp3',
		h3: 'square/h3.mp3',
		h4: 'square/h4.mp3',
		h5: 'square/h5.mp3',
		h6: 'square/h6.mp3',
		h7: 'square/h7.mp3',
		h8: 'square/h8.mp3',
	},
	modifier: {
		x: 'move_modifier/takes.mp3',
		'+': 'move_modifier/check.mp3',
		'#': 'move_modifier/mate.mp3',
		'=': 'move_modifier/equals.mp3',
	},
	fullMove: {
		'O-O': 'full_move/O-O.mp3',
		'O-O-O': 'full_move/O-O-O.mp3',
	},
	gameResult: {
		draw: 'game_result/draw.mp3',
		wins: 'game_result/wins.mp3',
	},
	gameDrawnReason: {
		'50 move-rule': 'game_drawn_reason/50 move-rule.mp3',
		agreement: 'game_drawn_reason/agreement.mp3',
		'insufficient material': 'game_drawn_reason/insufficient material.mp3',
		repetition: 'game_drawn_reason/repetition.mp3',
		stalemate: 'game_drawn_reason/stalemate.mp3',
	},
	gameWonReason: {
		checkmate: 'game_won_reason/checkmate.mp3',
		resignation: 'game_won_reason/resignation.mp3',
		time: 'game_won_reason/time.mp3',
	},
	misc: {
		by: 'misc/by.mp3',
		on: 'misc/on.mp3',
	},
}
